use_frameworks!

platform :ios, '10.0'

target 'MYEdiMobSDK_Example' do
  pod 'MYEdiMobSDK', :path => '../'

  target 'MYEdiMobSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
